//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitAirlines_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Reservations = new HashSet<Reservation>();
            this.ReservedSeats = new HashSet<ReservedSeat>();
        }
    
        public int FlightID { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string VoucherCode { get; set; }
        public Nullable<double> VoucherDiscountPercentage { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string PilotFullName { get; set; }
        public System.TimeSpan FlightDuration { get; set; }
        public double Price { get; set; }
        public string ShortInfo { get; set; }
        public byte[] Picture { get; set; }
        public string Notes { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Airport Airport { get; set; }
        public virtual City City { get; set; }
        public virtual User User { get; set; }
        public virtual MembershipType MembershipType { get; set; }
        public virtual Offer Offer { get; set; }
        public virtual Plane Plane { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservedSeat> ReservedSeats { get; set; }
    }
}
