//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitAirlines_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int GradeID { get; set; }
        public double GradeValue { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
