//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitAirlines_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MembershipType()
        {
            this.Flights = new HashSet<Flight>();
            this.Users = new HashSet<User>();
        }
    
        public int MembershipTypeID { get; set; }
        public string Title { get; set; }
        public string ShortInfo { get; set; }
        public double MembershipPrice { get; set; }
        public bool IsPriorityAvailable { get; set; }
        public bool IsExtraBaggageAvailable { get; set; }
        public bool IsFITSandwichAvailable { get; set; }
        public bool IsSeatChangeAvailable { get; set; }
        public bool IsBonusDrinkAvailable { get; set; }
        public bool IsBonusMealAvailable { get; set; }
        public double BasicTicketDiscount { get; set; }
        public double BasicFoodDrinkDiscount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight> Flights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
