//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitAirlines_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservedSeat
    {
        public int ReservedSeatID { get; set; }
        public string Direction { get; set; }
        public double SeatPrice { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Reservation Reservation { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
