// <auto-generated />
using System;
using FitAirlines.WebAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FitAirlines.WebAPI.Migrations
{
    [DbContext(typeof(FitAirlinesContext))]
    [Migration("20201227162737_Users_RemoveUserName")]
    partial class Users_RemoveUserName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FitAirlines.WebAPI.Database.Airports", b =>
                {
                    b.Property<int>("AirportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AirportID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AirportName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("CityId")
                        .HasColumnName("CityID");

                    b.Property<bool?>("IsAvailable")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("isAvailable")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("AirportId");

                    b.HasIndex("AirportName")
                        .IsUnique()
                        .HasName("UQ__Airports__4E72794649BB424C");

                    b.HasIndex("CityId");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("FitAirlines.WebAPI.Database.Cities", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CityID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("CountryId")
                        .HasColumnName("CountryID");

                    b.Property<byte[]>("Picture");

                    b.Property<string>("ShortInfo")
                        .HasMaxLength(400);

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("FitAirlines.WebAPI.Database.Countries", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CountryID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<byte[]>("Picture");

                    b.Property<string>("ShortInfo")
                        .HasMaxLength(400);

                    b.HasKey("CountryId");

                    b.HasIndex("CountryName")
                        .IsUnique()
                        .HasName("UQ__Countrie__E056F2015A80FCED");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("FitAirlines.WebAPI.Database.Flights", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("FlightID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddedByUserId")
                        .HasColumnName("AddedByUserID");

                    b.Property<DateTime>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("AvailableToMemberTypeId")
                        .HasColumnName("AvailableToMemberTypeID");

                    b.Property<int>("CityId")
                        .HasColumnName("CityID");

                    b.Property<int>("DestinationAirportId")
                        .HasColumnName("DestinationAirportID");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<TimeSpan>("FlightDuration");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Notes")
                        .HasMaxLength(400);

                    b.Property<int>("OfferId")
                        .HasColumnName("OfferID");

                    b.Property<byte[]>("Picture");

                    b.Property<string>("PilotFullName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("PlaneId")
                        .HasColumnName("PlaneID");

                    b.Property<double>("Price");

                    b.Property<string>("ShortInfo")
                        .HasMaxLength(400);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("VoucherCode")
                        .HasMaxLength(10);

                    b.Property<double?>("VoucherDiscountPercentage");

                    b.HasKey("FlightId");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("AvailableToMemberTypeId");

                    b.HasIndex("CityId");

                    b.HasIndex("DestinationAirportId");

                    b.HasIndex("OfferId");

                    b.HasIndex("PlaneId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("FitAirlines.WebAPI.Database.MembershipTypes", b =>
                {
                    b.Property<int>("MembershipTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MembershipTypeID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("BasicFoodDrinkDiscount");

                    b.Property<double>("BasicTicketDiscount");

                    b.Property<bool>("IsBonusDrinkAvailable");

                    b.Property<bool>("IsBonusMealAvailable");

                    b.Property<bool>("IsExtraBaggageAvailable");

                    b.Property<bool>("IsFitsandwichAvailable")
                        .HasColumnName("IsFITSandwichAvailable");

                    b.Property<bool>("IsPriorityAvailable");

                    b.Property<bool>("IsSeatChangeAvailable");

                    b.Property<double>("MembershipPrice");

                    b.Property<string>("ShortInfo")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("MembershipTypeId");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasName("UQ__Membersh__2CB664DCBC49163C");

                    b.ToTable("MembershipTypes");
                });

            modelBuilder.Entity("FitAirlines.WebAPI.Database.Offers", b =>
                {
                    b.Property<int>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("OfferID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("OfferName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("OfferTypeId")
                        .HasColumnName("OfferTypeID");

                    b.Property<byte[]>("Picture");

                    b.Property<string>("ShortInfo")
                        .HasMaxLength(400);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("OfferId");

                    b.HasIndex("OfferName")
                        .IsUnique()
                        .HasName("UQ__Offers__07109364D9E5093F");

                    b.HasIndex("OfferTypeId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("FitAirlines.WebAPI.Database.OfferTypes", b =>
                {
                    b.Property<int>("OfferTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("OfferTypeID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeDescription")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("OfferTypeId");

                    b.HasIndex("TypeName")
                        .IsUnique()
                        .HasName("UQ__OfferTyp__D4E7DFA86FF56EF0");

                    b.ToTable("OfferTypes");
                });

            modelBuilder.Entity("FitAirlines.WebAPI.Database.Planes", b =>
                {
                    b.Property<int>("PlaneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PlaneID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity");

                    b.Property<bool?>("IsAvailable")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((1))");

                    b.Property<int>("NumberOfColumns")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((6))");

                    b.Property<string>("PlaneName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("PlaneId");

                    b.HasIndex("PlaneName")
                        .IsUnique()
                        .HasName("UQ__Planes__7372E2C6E4398C69");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("FitAirlines.WebAPI.Database.Ratings", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RatingID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Notes")
                        .HasMaxLength(200);

                    b.Property<double>("RatingValue");

                    b.Property<int>("ReservationId")
                        .HasColumnName("ReservationID");

                    b.HasKey("RatingId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("FitAirlines.WebAPI.Database.Reservations", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ReservationID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("BaseTicketPrice");

                    b.Property<int?>("CashierId")
                        .HasColumnName("CashierID");

                    b.Property<int>("FlightId")
                        .HasColumnName("FlightID");

                    b.Property<bool?>("IsValid")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Notes")
                        .HasMaxLength(100);

                    b.Property<DateTime>("ReservationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<double>("TotalDiscountPercentage");

                    b.Property<int>("UserId")
                        .HasColumnName("UserID");

                    b.HasKey("ReservationId");

                    b.HasIndex("CashierId");

                    b.HasIndex("FlightId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("FitAirlines.WebAPI.Database.ReservedSeats", b =>
                {
                    b.Property<int>("ReservedSeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ReservedSeatID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(5);

                    b.Property<int>("FlightId")
                        .HasColumnName("FlightID");

                    b.Property<int>("ReservationId")
                        .HasColumnName("ReservationID");

                    b.Property<int>("SeatColumn");

                    b.Property<double>("SeatPrice");

                    b.Property<int>("SeatRow");

                    b.HasKey("ReservedSeatId");

                    b.HasIndex("FlightId");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservedSeats");
                });

            modelBuilder.Entity("FitAirlines.WebAPI.Database.UserRoles", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserRoleID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAbleToAddNewFlights");

                    b.Property<bool>("IsAbleToAddNewOffers");

                    b.Property<bool>("IsAbleToAddNewPlaces");

                    b.Property<bool>("IsAbleToAddNewPlanes");

                    b.Property<bool>("IsAbleToAddNewReservations");

                    b.Property<bool>("IsAbleToAddNewUsers");

                    b.Property<bool>("IsAbleToAddUserCredits");

                    b.Property<bool>("IsSuperUser");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("UserRoleId");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasName("UQ__UserRole__2CB664DCF252F501");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("FitAirlines.WebAPI.Database.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double>("Credit");

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("isActive")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("MembershipTypeId")
                        .HasColumnName("MembershipTypeID");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("('')")
                        .HasMaxLength(100);

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("('')")
                        .HasMaxLength(100);

                    b.Property<byte[]>("Picture");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserRoleId")
                        .HasColumnName("UserRoleID");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasName("UQ__Users__A9D10534A6A00C66")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("MembershipTypeId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FitAirlines.WebAPI.Database.Airports", b =>
                {
                    b.HasOne("FitAirlines.WebAPI.Database.Cities", "City")
                        .WithMany("Airports")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK__Airports__CityID__2C3393D0");
                });

            modelBuilder.Entity("FitAirlines.WebAPI.Database.Cities", b =>
                {
                    b.HasOne("FitAirlines.WebAPI.Database.Countries", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("FK__Cities__CountryI__276EDEB3");
                });

            modelBuilder.Entity("FitAirlines.WebAPI.Database.Flights", b =>
                {
                    b.HasOne("FitAirlines.WebAPI.Database.Users", "AddedByUser")
                        .WithMany("Flights")
                        .HasForeignKey("AddedByUserId")
                        .HasConstraintName("FK__Flights__AddedBy__5165187F");

                    b.HasOne("FitAirlines.WebAPI.Database.MembershipTypes", "AvailableToMemberType")
                        .WithMany("Flights")
                        .HasForeignKey("AvailableToMemberTypeId")
                        .HasConstraintName("FK__Flights__Availab__534D60F1");

                    b.HasOne("FitAirlines.WebAPI.Database.Cities", "City")
                        .WithMany("Flights")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK__Flights__CityID__4D94879B");

                    b.HasOne("FitAirlines.WebAPI.Database.Airports", "DestinationAirport")
                        .WithMany("Flights")
                        .HasForeignKey("DestinationAirportId")
                        .HasConstraintName("FK__Flights__Destina__4E88ABD4");

                    b.HasOne("FitAirlines.WebAPI.Database.Offers", "Offer")
                        .WithMany("Flights")
                        .HasForeignKey("OfferId")
                        .HasConstraintName("FK__Flights__OfferID__4F7CD00D");

                    b.HasOne("FitAirlines.WebAPI.Database.Planes", "Plane")
                        .WithMany("Flights")
                        .HasForeignKey("PlaneId")
                        .HasConstraintName("FK__Flights__PlaneID__5070F446");
                });

            modelBuilder.Entity("FitAirlines.WebAPI.Database.Offers", b =>
                {
                    b.HasOne("FitAirlines.WebAPI.Database.OfferTypes", "OfferType")
                        .WithMany("Offers")
                        .HasForeignKey("OfferTypeId")
                        .HasConstraintName("FK__Offers__OfferTyp__398D8EEE");
                });

            modelBuilder.Entity("FitAirlines.WebAPI.Database.Ratings", b =>
                {
                    b.HasOne("FitAirlines.WebAPI.Database.Reservations", "Reservation")
                        .WithMany("Ratings")
                        .HasForeignKey("ReservationId")
                        .HasConstraintName("FK__Ratings__Reserva__5EBF139D");
                });

            modelBuilder.Entity("FitAirlines.WebAPI.Database.Reservations", b =>
                {
                    b.HasOne("FitAirlines.WebAPI.Database.Users", "Cashier")
                        .WithMany("ReservationsCashier")
                        .HasForeignKey("CashierId")
                        .HasConstraintName("FK__Reservati__Cashi__5BE2A6F2");

                    b.HasOne("FitAirlines.WebAPI.Database.Flights", "Flight")
                        .WithMany("Reservations")
                        .HasForeignKey("FlightId")
                        .HasConstraintName("FK__Reservati__Fligh__5812160E");

                    b.HasOne("FitAirlines.WebAPI.Database.Users", "User")
                        .WithMany("ReservationsUser")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Reservati__UserI__571DF1D5");
                });

            modelBuilder.Entity("FitAirlines.WebAPI.Database.ReservedSeats", b =>
                {
                    b.HasOne("FitAirlines.WebAPI.Database.Flights", "Flight")
                        .WithMany("ReservedSeats")
                        .HasForeignKey("FlightId")
                        .HasConstraintName("FK__ReservedS__Fligh__6383C8BA");

                    b.HasOne("FitAirlines.WebAPI.Database.Reservations", "Reservation")
                        .WithMany("ReservedSeats")
                        .HasForeignKey("ReservationId")
                        .HasConstraintName("FK__ReservedS__Reser__628FA481");
                });

            modelBuilder.Entity("FitAirlines.WebAPI.Database.Users", b =>
                {
                    b.HasOne("FitAirlines.WebAPI.Database.MembershipTypes", "MembershipType")
                        .WithMany("Users")
                        .HasForeignKey("MembershipTypeId")
                        .HasConstraintName("FK__Users__Membershi__4AB81AF0");

                    b.HasOne("FitAirlines.WebAPI.Database.UserRoles", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .HasConstraintName("FK__Users__UserRoleI__49C3F6B7");
                });
#pragma warning restore 612, 618
        }
    }
}
