//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitAirlines.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitAirlines.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new flight.
        /// </summary>
        public static string AddFlight_FormName {
            get {
                return ResourceManager.GetString("AddFlight_FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new offer.
        /// </summary>
        public static string AddOffer_FormName {
            get {
                return ResourceManager.GetString("AddOffer_FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic info.
        /// </summary>
        public static string AddOrEditFlight_BasicInfo {
            get {
                return ResourceManager.GetString("AddOrEditFlight_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string AddOrEditFlight_Capacity {
            get {
                return ResourceManager.GetString("AddOrEditFlight_Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string AddOrEditFlight_City {
            get {
                return ResourceManager.GetString("AddOrEditFlight_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string AddOrEditFlight_Country {
            get {
                return ResourceManager.GetString("AddOrEditFlight_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string AddOrEditFlight_EndDate {
            get {
                return ResourceManager.GetString("AddOrEditFlight_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AddOrEditFlight_FlightDescription {
            get {
                return ResourceManager.GetString("AddOrEditFlight_FlightDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight name.
        /// </summary>
        public static string AddOrEditFlight_FlightName {
            get {
                return ResourceManager.GetString("AddOrEditFlight_FlightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight offer.
        /// </summary>
        public static string AddOrEditFlight_FlightOffer {
            get {
                return ResourceManager.GetString("AddOrEditFlight_FlightOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string AddOrEditFlight_StartDate {
            get {
                return ResourceManager.GetString("AddOrEditFlight_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Options.
        /// </summary>
        public static string AddOrEditOffer_ImageOptions {
            get {
                return ResourceManager.GetString("AddOrEditOffer_ImageOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AddOrEditOffer_OfferDescription {
            get {
                return ResourceManager.GetString("AddOrEditOffer_OfferDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min membership level.
        /// </summary>
        public static string AddOrEditOFfer_OfferMembershipLevel {
            get {
                return ResourceManager.GetString("AddOrEditOFfer_OfferMembershipLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer title.
        /// </summary>
        public static string AddOrEditOffer_OfferName {
            get {
                return ResourceManager.GetString("AddOrEditOffer_OfferName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal info.
        /// </summary>
        public static string AddOrEditOffer_PersonalInfo {
            get {
                return ResourceManager.GetString("AddOrEditOffer_PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string AddOrEditReservation_Client {
            get {
                return ResourceManager.GetString("AddOrEditReservation_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string AddOrEditReservation_Discount {
            get {
                return ResourceManager.GetString("AddOrEditReservation_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight.
        /// </summary>
        public static string AddOrEditReservation_Flight {
            get {
                return ResourceManager.GetString("AddOrEditReservation_Flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        public static string AddOrEditReservation_Offer {
            get {
                return ResourceManager.GetString("AddOrEditReservation_Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string AddOrEditReservation_Paid {
            get {
                return ResourceManager.GetString("AddOrEditReservation_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string AddOrEditReservation_Price {
            get {
                return ResourceManager.GetString("AddOrEditReservation_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price.
        /// </summary>
        public static string AddOrEditReservation_PriceTitle {
            get {
                return ResourceManager.GetString("AddOrEditReservation_PriceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat (return).
        /// </summary>
        public static string AddOrEditReservation_SeatReturn {
            get {
                return ResourceManager.GetString("AddOrEditReservation_SeatReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat (start).
        /// </summary>
        public static string AddOrEditReservation_SeatStart {
            get {
                return ResourceManager.GetString("AddOrEditReservation_SeatStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string AddOrEditUser_AccountBalance {
            get {
                return ResourceManager.GetString("AddOrEditUser_AccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string AddOrEditUser_Actions {
            get {
                return ResourceManager.GetString("AddOrEditUser_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add credit.
        /// </summary>
        public static string AddOrEditUser_AddCredit {
            get {
                return ResourceManager.GetString("AddOrEditUser_AddCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string AddOrEditUser_BirthDate {
            get {
                return ResourceManager.GetString("AddOrEditUser_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AddOrEditUser_Cancel {
            get {
                return ResourceManager.GetString("AddOrEditUser_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Picture.
        /// </summary>
        public static string AddOrEditUser_ChangeProfilePicture {
            get {
                return ResourceManager.GetString("AddOrEditUser_ChangeProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string AddOrEditUser_FirstName {
            get {
                return ResourceManager.GetString("AddOrEditUser_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIT membership.
        /// </summary>
        public static string AddOrEditUser_FitMembership {
            get {
                return ResourceManager.GetString("AddOrEditUser_FitMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string AddOrEditUser_Gender {
            get {
                return ResourceManager.GetString("AddOrEditUser_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is active.
        /// </summary>
        public static string AddOrEditUser_IsActive {
            get {
                return ResourceManager.GetString("AddOrEditUser_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string AddOrEditUser_LastName {
            get {
                return ResourceManager.GetString("AddOrEditUser_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal info.
        /// </summary>
        public static string AddOrEditUser_PersonalInfoGroupBox {
            get {
                return ResourceManager.GetString("AddOrEditUser_PersonalInfoGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile picture.
        /// </summary>
        public static string AddOrEditUser_ProfilePictureGroupBox {
            get {
                return ResourceManager.GetString("AddOrEditUser_ProfilePictureGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string AddOrEditUser_Save {
            get {
                return ResourceManager.GetString("AddOrEditUser_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new reservation.
        /// </summary>
        public static string AddReservation_FormName {
            get {
                return ResourceManager.GetString("AddReservation_FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        public static string AddUser_FormName {
            get {
                return ResourceManager.GetString("AddUser_FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit flight.
        /// </summary>
        public static string EditFlight_FormName {
            get {
                return ResourceManager.GetString("EditFlight_FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit offer.
        /// </summary>
        public static string EditOffer_FormName {
            get {
                return ResourceManager.GetString("EditOffer_FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit reservation.
        /// </summary>
        public static string EditReservation_FormName {
            get {
                return ResourceManager.GetString("EditReservation_FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string EditUser_FormName {
            get {
                return ResourceManager.GetString("EditUser_FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight date.
        /// </summary>
        public static string Flights_FlightDate {
            get {
                return ResourceManager.GetString("Flights_FlightDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight name.
        /// </summary>
        public static string Flights_FlightName {
            get {
                return ResourceManager.GetString("Flights_FlightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flights.
        /// </summary>
        public static string Flights_FormName {
            get {
                return ResourceManager.GetString("Flights_FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        public static string Flights_Offer {
            get {
                return ResourceManager.GetString("Flights_Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Generic_Add {
            get {
                return ResourceManager.GetString("Generic_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Generic_Edit {
            get {
                return ResourceManager.GetString("Generic_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image options.
        /// </summary>
        public static string Generic_ImageOptions {
            get {
                return ResourceManager.GetString("Generic_ImageOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only active items.
        /// </summary>
        public static string Generic_IsActive {
            get {
                return ResourceManager.GetString("Generic_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Generic_Save {
            get {
                return ResourceManager.GetString("Generic_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Generic_Search {
            get {
                return ResourceManager.GetString("Generic_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload image....
        /// </summary>
        public static string Generic_UploadImage {
            get {
                return ResourceManager.GetString("Generic_UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hand {
            get {
                object obj = ResourceManager.GetObject("hand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Icon_Add {
            get {
                object obj = ResourceManager.GetObject("Icon_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Icon_Settings {
            get {
                object obj = ResourceManager.GetObject("Icon_Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_Placeholder {
            get {
                object obj = ResourceManager.GetObject("Image_Placeholder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flights.
        /// </summary>
        public static string MainMenu_Flights {
            get {
                return ResourceManager.GetString("MainMenu_Flights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        public static string MainMenu_FormName {
            get {
                return ResourceManager.GetString("MainMenu_FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        public static string MainMenu_Offers {
            get {
                return ResourceManager.GetString("MainMenu_Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.
        /// </summary>
        public static string MainMenu_Reservations {
            get {
                return ResourceManager.GetString("MainMenu_Reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainMenu_Settings {
            get {
                return ResourceManager.GetString("MainMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string MainMenu_Users {
            get {
                return ResourceManager.GetString("MainMenu_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        public static string Offers_FormName {
            get {
                return ResourceManager.GetString("Offers_FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer date:.
        /// </summary>
        public static string Offers_OfferDate {
            get {
                return ResourceManager.GetString("Offers_OfferDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer name:.
        /// </summary>
        public static string Offers_OfferName {
            get {
                return ResourceManager.GetString("Offers_OfferName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Reservations_ClientName {
            get {
                return ResourceManager.GetString("Reservations_ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight.
        /// </summary>
        public static string Reservations_Flight {
            get {
                return ResourceManager.GetString("Reservations_Flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight date.
        /// </summary>
        public static string Reservations_FlightDate {
            get {
                return ResourceManager.GetString("Reservations_FlightDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.
        /// </summary>
        public static string Reservations_FormName {
            get {
                return ResourceManager.GetString("Reservations_FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation date.
        /// </summary>
        public static string Reservations_ReservationDate {
            get {
                return ResourceManager.GetString("Reservations_ReservationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users_FormName {
            get {
                return ResourceManager.GetString("Users_FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Users_Gender {
            get {
                return ResourceManager.GetString("Users_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Level.
        /// </summary>
        public static string Users_MemberLevel {
            get {
                return ResourceManager.GetString("Users_MemberLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name / Last name.
        /// </summary>
        public static string Users_NameSurname {
            get {
                return ResourceManager.GetString("Users_NameSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is not in valid format..
        /// </summary>
        public static string Validation_EmailInvalid {
            get {
                return ResourceManager.GetString("Validation_EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string Validation_FieldRequired {
            get {
                return ResourceManager.GetString("Validation_FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number is not in valid format..
        /// </summary>
        public static string Validation_PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("Validation_PhoneNumberInvalid", resourceCulture);
            }
        }
    }
}
